# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - '**'
      - '!latest'
    pull_request: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

        
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_DEPLOY_TOKEN }}
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: meekrosoft
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_DEPLOY_TOKEN }}
        # Docker repository to tag the image with
        repository: merkely/change
        tags: master
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: TRUE
        add_git_labels: TRUE

    - name: Get the sha7
      id: shortsha
      run: |
        echo ::set-output name=value::$(git log -1 --pretty=%h)

    - name: Declare the pipeline and log docker-image artifact information to Merkely
      env:
        export SHA7="${{ steps.shortsha.outputs.value }}"
        MERKELY_FINGERPRINT: docker://merkely/change:sha-${SHA7}
        MERKELY_ARTIFACT_GIT_URL: https://github.com/compliancedb/cdb_controls/commit/${GITHUB_SHA}
        MERKELY_ARTIFACT_GIT_COMMIT: ${GITHUB_SHA}
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_CI_BUILD_NUMBER: ${GITHUB_RUN_ID}
        MERKELY_IS_COMPLIANT: 'TRUE'
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        #export SHA7=$(git log -1 --pretty=%h)
        #export MERKELY_DOCKER_IMAGE=merkely/change:sha-${SHA7}
        make branch merkely_declare_pipeline merkely_log_artifact

    - name: Log the deployment in Merkely
      env:
        MERKELY_DOCKER_IMAGE: merkely/change:sha-${SHA7}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
        MERKELY_IS_COMPLIANT: 'TRUE'
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_DESCRIPTION: "Deployment of ${MERKELY_DOCKER_IMAGE} to docker hub"
        MERKELY_ENVIRONMENT: 'docker_hub'
      run: |
        export SHA7=$(git log -1 --pretty=%h)
        #export CDB_ARTIFACT_DOCKER_IMAGE=merkely/change:sha-${SHA7}
        #export CDB_DESCRIPTION="Deployment of ${CDB_ARTIFACT_DOCKER_IMAGE} to docker hub"
        make merkely_log_deployment

    - name: Run unit tests
      env:
        CDB_API_TOKEN: ${{ secrets.CDB_API_TOKEN }}
      run: |
        make build_all test_all

    - name: Merkely Control Unit Test Results
      env:
        CDB_API_TOKEN: ${{ secrets.CDB_API_TOKEN }}
        CDB_HOST: https://app.compliancedb.com
        CDB_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
      run: |
        export SHA7=$(git log -1 --pretty=%h)
        export CDB_ARTIFACT_DOCKER_IMAGE=merkely/change:sha-${SHA7}

        export CDB_TEST_RESULTS=${PWD}/tmp/coverage/unit/htmlcov/junit.xml
        export CDB_EVIDENCE_TYPE="unit_test"
        make control_and_publish_junit_results

        export CDB_TEST_RESULTS=${PWD}/tmp/coverage/integration/htmlcov/junit.xml
        export CDB_EVIDENCE_TYPE="integration_test"
        make control_and_publish_junit_results

    - name: Merkely Control Unit Test Results
      env:
        CDB_API_TOKEN: ${{ secrets.CDB_API_TOKEN }}
        CDB_HOST: https://app.compliancedb.com
        CDB_EVIDENCE_TYPE: "integration_test"
        CDB_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
      run: |
        export SHA7=$(git log -1 --pretty=%h)
        export CDB_ARTIFACT_DOCKER_IMAGE=merkely/change:sha-${SHA7}
        make control_and_publish_junit_results


    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: tmp/coverage/

    - name: Publish coverage results to Merkely
      env:
        CDB_API_TOKEN: ${{ secrets.CDB_API_TOKEN }}
        CDB_HOST: https://app.compliancedb.com
        CDB_IS_COMPLIANT: 'TRUE'
        CDB_EVIDENCE_TYPE: "coverage"
        CDB_BUILD_NUMBER: ${GITHUB_RUN_ID}
        CDB_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}

        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
        MERKELY_IS_COMPLIANT: 'TRUE'
        MERKELY_EVIDENCE_TYPE: "coverage"
        MERKELY_DOCKER_IMAGE: merkely/change:sha-${SHA7}
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}

      run: |
        export SHA7=$(git log -1 --pretty=%h)
        export CDB_ARTIFACT_DOCKER_IMAGE=merkely/change:sha-${SHA7}
        source tmp/coverage/unit/htmlcov/test_coverage.txt
        source tmp/coverage/unit/htmlcov/test_cases.txt
        export CDB_DESCRIPTION="$TEST_CASES tests passed with $COVERAGE coverage"
        export MERKELY_DESCRIPTION="${TEST_CASES} tests passed with ${COVERAGE} coverage"
        make publish_test_results