name: CI

on:
  push:
    branches:
      - '**'
      - '!latest'
    pull_request: []


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Set long sha env-var
      run: echo "LONG_SHA=$(git log -1 --pretty=%H)" >> ${GITHUB_ENV}
    - name: Set short sha env-var
      run: echo "SHORT_SHA=${LONG_SHA:0:7}" >> ${GITHUB_ENV}
    - name: Set tagged-image sha env-var
      run: echo "TAGGED_IMAGE=merkely/change:sha-${SHORT_SHA}" >> ${GITHUB_ENV}
    - name: Set merkely-fingerprint env-var
      run: echo "MERKELY_FINGERPRINT=docker://${TAGGED_IMAGE}" >> ${GITHUB_ENV}


    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_DEPLOY_TOKEN }}
      with:
        build_args: IMAGE_COMMIT_SHA=${{ env.LONG_SHA }}
        username: meekrosoft
        password: ${{ secrets.DOCKER_DEPLOY_TOKEN }}
        repository: merkely/change
        tags: master
        tag_with_sha: TRUE
        add_git_labels: TRUE


    - name: Declare Merkely pipeline
      env:
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        make branch
        make merkely_declare_pipeline


    - name: Log Docker image to Merkely
      env:
        MERKELY_IS_COMPLIANT: 'TRUE'
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        make merkely_log_artifact


    - name: Log image deployment to Merkely
      env:
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_DESCRIPTION: "Deployment of ${TAGGED_IMAGE} to docker hub"
        MERKELY_ENVIRONMENT: 'docker_hub'
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        make merkely_log_deployment


    - name: Run tests
      run: |
        make build_all test_all


    - name: Log test results to Merkely
      env:
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}

      run: |
        export TEST_RESULTS_FILE=${PWD}/tmp/coverage/unit/htmlcov/junit.xml
        export MERKELY_EVIDENCE_TYPE="unit_test"
        make merkely_log_test

        export TEST_RESULTS_FILE=${PWD}/tmp/coverage/integration/htmlcov/junit.xml
        export MERKELY_EVIDENCE_TYPE="integration_test"
        make merkely_log_test


    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: tmp/coverage/


    - name: Log coverage evidence to Merkely
      env:
        MERKELY_EVIDENCE_TYPE: "coverage"
        MERKELY_IS_COMPLIANT: 'TRUE'
        MERKELY_CI_BUILD_URL: https://github.com/compliancedb/cdb_controls/actions/runs/${GITHUB_RUN_ID}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        source tmp/coverage/unit/htmlcov/test_coverage.sh
        source tmp/coverage/unit/htmlcov/test_cases.sh
        export MERKELY_DESCRIPTION="${TEST_CASES} tests passed with ${COVERAGE} coverage"
        make merkely_log_evidence