name: Release

on:
  push:
    tags:
      - release-*

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch full history
          fetch-depth: 0


      - name: Set Docker image name and short sha as environment variables
        run: |
          echo "UNTAGGED_IMAGE=merkely/change"     >> ${GITHUB_ENV}
          echo "TAG=sha-$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


      - name: Approve deployment in Merkely, update latest docker image and git branch
        env:
          MERKELY_FINGERPRINT: docker://${UNTAGGED_IMAGE}:latest
          MERKELY_NEWEST_SRC_COMMITISH: ${GITHUB_SHA}
          MERKELY_OLDEST_SRC_COMMITISH: "origin/latest"
          MERKELY_DESCRIPTION: "Approval created in github actions on git tag ${GITHUB_REF}"
          MERKELY_OWNER: ${{ secrets.MERKELY_OWNER }}
          MERKELY_PIPELINE: ${{ secrets.MERKELY_PIPELINE }}
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
        run: |
          make merkely_approve_deployment

          # Deploy latest docker image
          docker pull ${UNTAGGED_IMAGE}:${TAG}
          docker tag ${UNTAGGED_IMAGE}:${TAG} ${UNTAGGED_IMAGE}:latest
          docker login -u meekrosoft -p ${{ secrets.DOCKER_DEPLOY_TOKEN }}
          docker push ${UNTAGGED_IMAGE}:latest

          git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cblue%d %Creset %s %C(bold)(%an)%Creset" | head -n 30

          # update git branch
          # Merge latest -> master
          git checkout latest
          git merge --ff-only ${GITHUB_SHA}
          git push origin latest


      - name: Log the deployment in Merkely
        env:
          MERKELY_FINGERPRINT: docker://${UNTAGGED_IMAGE}:latest
          MERKELY_DESCRIPTION: "Deployment of ${UNTAGGED_IMAGE}:latest to docker hub"
          MERKELY_ENVIRONMENT: "docker_hub"
          MERKELY_OWNER: ${{ secrets.MERKELY_OWNER }}
          MERKELY_PIPELINE: ${{ secrets.MERKELY_PIPELINE }}
          MERKELY_API_TOKEN: ${{ secrets.CDB_API_TOKEN }}
        run: |
          make merkely_log_deployment